# Generated by Django 3.1.1 on 2020-09-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0002_lesson_zoom_start_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='zum_url',
            new_name='zoom_join_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='zoom_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
