# Generated by Django 3.1.1 on 2020-09-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_auto_20200911_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoninfo',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonInfo',
        ),
        migrations.DeleteModel(
            name='LessonTime',
        ),
        migrations.DeleteModel(
            name='LessonType',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
    ]
